## Task:
Write a function to solve equtions of any unknown

In [ ]:
#THIS ONE GET ALL THE COEFFICIENTS OF JUST ONE PARTICULAR UNKNOWN BEFORE THE NEXT

import numpy as np

def get_coefficients(no_of_unknowns,no_of_unknowns_collected):
    '''Prompt the user to enter all the coefficients of an unknown(e.g x) in all the equation(s)'''
    x= []
    print('Enter all the coefficients of X%s: '%(no_of_unknowns_collected+1))
    for unknown in range(1,no_of_unknowns+1):
        k = int(input())
        x.append(k)
    x = np.array(x).reshape((no_of_unknowns,1))         
    return(x)

def get_constants(no_of_unknowns):
    '''Prompt the user to enter all the constants in all the equation(s)'''
    x= []
    print('Enter all the constants: ')
    for unknown in range(1,no_of_unknowns+1):
        k = int(input())
        x.append(k)
    x = np.array(x).reshape((no_of_unknowns,1))         
    return(x) 
    
    
#Get the number of unknowns to be solved from user
no_of_unknowns = int(input('Enter the number of unknowns to solve: '))
#using the mathematics logic of (x = A**-1 * B)
A = np.zeros((no_of_unknowns,no_of_unknowns))#creating an arbituary array for A
A = np.asmatrix(A)
B = np.zeros((no_of_unknowns,1))


no_of_unknowns_collected = 0
while no_of_unknowns_collected < no_of_unknowns:
    #iterating over to collect all the coefficeint of all unknowns
    A[:,(no_of_unknowns_collected)] = get_coefficients(no_of_unknowns,no_of_unknowns_collected)
    no_of_unknowns_collected +=1
print(A)

#collecting all the constants
print('Enter the constants values respectively: ')
B = get_constants(no_of_unknowns)
B = np.asmatrix(B)
print(B)

unknown_values = (A**(-1))*B
print('The values of the unknowns X(%s) are %s respectively'%(range(1,no_of_unknowns+1),unknown_values))

In [5]:
#THIS GET THE COEFFIECENTS OF UNKNOWN(S) FOR EACH EQUATION

import numpy as np

def get_coefficients(no_of_unknowns):
    '''Prompt the user to enter the coefficients of the unknown in the equation'''
    print('Equation...%s'%(no_of_equations+1))
    x= []
    for unknown in range(1,no_of_unknowns+1):
    #iterate through to get the coeffients
        k = int(input('Enter the coefficients of X%s: '%(unknown)))
        x.append(k)
    x = np.array(x)        
    return(x)  

def get_constant(no_of_unknowns):
    '''Returns the constant in each equation'''
    k = int(input('Enter the constant of the equation: '))
    return(k)
    
    
    
no_of_unknowns = int(input('Enter the number of unknowns to solve: '))
A = np.zeros((no_of_unknowns,no_of_unknowns))#arbituary space for the inputs
B = np.zeros((no_of_unknowns,1))

no_of_equations = 0
for unknown in range(no_of_unknowns):
    A[unknown,:] = get_coefficients(no_of_unknowns)
    B[unknown] = get_constant(no_of_unknowns)
    no_of_equations +=1
print('%s * X(unknowns) = %s'%(A,B))



unknown_values = np.linalg.inv(A).dot(B)
print('The values of the unknowns(X) are %s respectively'%(unknown_values))

Enter the number of unknowns to solve: 4
Equation...1
Enter the coefficients of X1: 3
Enter the coefficients of X2: -2
Enter the coefficients of X3: -4
Enter the coefficients of X4: 1
Enter the constant of the equation: 5
Equation...2
Enter the coefficients of X1: -1
Enter the coefficients of X2: 5
Enter the coefficients of X3: 9
Enter the coefficients of X4: -10
Enter the constant of the equation: 6
Equation...3
Enter the coefficients of X1: 0
Enter the coefficients of X2: -6
Enter the coefficients of X3: 7
Enter the coefficients of X4: -6
Enter the constant of the equation: 5
Equation...4
Enter the coefficients of X1: 8
Enter the coefficients of X2: -2
Enter the coefficients of X3: 3
Enter the coefficients of X4: 4
Enter the constant of the equation: 1
[[  3.  -2.  -4.   1.]
 [ -1.   5.   9. -10.]
 [  0.  -6.   7.  -6.]
 [  8.  -2.   3.   4.]] * X(unknowns) = [[5.]
 [6.]
 [5.]
 [1.]]
The values of the unknowns(X) are [[ 1.06354009]
 [-0.21079173]
 [-0.70953101]
 [-1.45032779]] respec